directories:
  output: bin
  buildResources: build
appId: com.qmtpro.terminal
productName: QMTerminal
win:
  target: portable
  artifactName: QMTerminal.exe
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
electronVersion: 25.9.8
